name: iOS CI with CocoaPods

on: workflow_dispatch

jobs:
  iOS:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.4,name=iPhone 12 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
    - uses: actions/checkout@v2
    - name: Install CocoaPods
      run: | 
        pod --version
        cd example
        pod install --repo-update
    - name: Scheme Shared
      run: |
        cp -r Shared/xcshareddata Example/Pods/Pods.xcodeproj
        rm -rf Example/Pods/Pods.xcodeproj/xcuserdata/*/*/*.xcscheme
    - name: Carthage build
      run: |
        carthage build --no-skip-current --use-xcframeworks
        cp -r Carthage/Build/*.xcframework Framework/
    - name: Git push
      run: |
        git status
        git add .
        git commit -m "[framework] update xcframework"
        git tag "0.63.4.3"
        git pull origin
        git push origin
        git push origin --tags
    - name: Pod register
      run: pod trunk register liamxujia@outlook.com 'liamxujia' --description='GitHub register to trunk.'
    - name: Pod trunk
      run: pod trunk push react-ios.podspec --allow-warnings --verbose
